// ─── Plans Domain: Activity Catalog V4 ───────────────────────────────────────
// 160 activities fully tagged for the Plans decision engine.
// India-focused — Tier 1 + Tier 2 cities.
// Schema: id, name, category, location, kidsFriendly, budget, timeNeeded,
//         energyLevel, groupTypes, vibes, cityType, weatherSafe,
//         noveltyScore, effortScore, popularityScore, timeOfDay,
//         actionType, mapQuery
//
// timeNeeded values: "1-2hr" | "2-4hr" | "half-day" | "full-day"
// timeOfDay values:  "morning" | "afternoon" | "evening" | "night"
// actionType values: "maps" | "rules" | "watch" | null

export const ACTIVITY_CATALOG = [

  // ─── CATEGORY 1: MOVIES / ENTERTAINMENT ──────────────────────────

  {
    id: 1,
    name: "Movie Outing",
    category: "movies",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "watch",
    mapQuery: null,
  },
  {
    id: 2,
    name: "Drive-in Movie",
    category: "movies",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","fun"],
    cityType: "metro-only",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["evening","night"],
    actionType: "watch",
    mapQuery: null,
  },
  {
    id: 3,
    name: "IMAX Experience",
    category: "movies",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "watch",
    mapQuery: null,
  },
  {
    id: 4,
    name: "Regional Cinema Night",
    category: "movies",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "watch",
    mapQuery: null,
  },
  {
    id: 5,
    name: "Open-Air Movie Screening",
    category: "movies",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","fun"],
    cityType: "metro-only",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["evening","night"],
    actionType: "watch",
    mapQuery: null,
  },

  // ─── CATEGORY 2: FOOD + CHILL ────────────────────────────────────

  {
    id: 6,
    name: "Cafe + Dessert",
    category: "food-chill",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "cafe dessert",
  },
  {
    id: 7,
    name: "Rooftop Dinner",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: false,
    budget: "high",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["relax","food-chill"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["evening","night"],
    actionType: "maps",
    mapQuery: "rooftop dinner restaurant",
  },
  {
    id: 8,
    name: "Street Food Walk",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun","food-chill","adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "street food",
  },
  {
    id: 9,
    name: "Breakfast Ride",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends"],
    vibes: ["fun","food-chill","adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning"],
    actionType: "maps",
    mapQuery: "breakfast cafe",
  },
  {
    id: 10,
    name: "Buffet Lunch",
    category: "food-chill",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon"],
    actionType: "maps",
    mapQuery: "buffet restaurant",
  },
  {
    id: 11,
    name: "Tea + Snacks Adda",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "chai tapri snacks",
  },
  {
    id: 12,
    name: "Midnight Food Drive",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["fun","food-chill","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["night"],
    actionType: "maps",
    mapQuery: "late night food",
  },
  {
    id: 13,
    name: "Dessert Hopping",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun","food-chill"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "dessert cafe",
  },
  {
    id: 14,
    name: "Food Truck Evening",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun","food-chill"],
    cityType: "metro-only",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["evening","night"],
    actionType: "maps",
    mapQuery: "food truck",
  },
  {
    id: 15,
    name: "Fine Dining Night",
    category: "food-chill",
    location: "indoor",
    kidsFriendly: false,
    budget: "high",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["relax","food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["evening","night"],
    actionType: "maps",
    mapQuery: "fine dining restaurant",
  },
  {
    id: 16,
    name: "Family Restaurant Dinner",
    category: "food-chill",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family","friends"],
    vibes: ["relax","food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon","evening"],
    actionType: "maps",
    mapQuery: "family restaurant",
  },
  {
    id: 17,
    name: "Live Music Cafe",
    category: "food-chill",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["relax","fun","food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["evening","night"],
    actionType: "maps",
    mapQuery: "live music cafe",
  },
  {
    id: 18,
    name: "Chai Tapri Hangout",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["relax","food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "chai tapri",
  },
  {
    id: 19,
    name: "Themed Cafe Visit",
    category: "food-chill",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun","food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon","evening"],
    actionType: "maps",
    mapQuery: "themed cafe",
  },
  {
    id: 20,
    name: "Pet Cafe Visit",
    category: "food-chill",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","fun","food-chill"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "pet cafe",
  },
  {
    id: 101,
    name: "Temple + Breakfast",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","evening","night"],
    actionType: "maps",
    mapQuery: "temple breakfast",
  },
  {
    id: 102,
    name: "Flea + Food Market",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun","food-chill","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "flea market food",
  },
  {
    id: 147,
    name: "Market Walk + Dinner",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun","food-chill","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon","evening"],
    actionType: "maps",
    mapQuery: "local market street food",
  },

  // ─── CATEGORY 3: FUN INDOOR ACTIVITIES ───────────────────────────

  {
    id: 21,
    name: "Bowling",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "bowling alley",
  },
  {
    id: 22,
    name: "Arcade / Gaming Zone",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "arcade gaming zone",
  },
  {
    id: 23,
    name: "VR Gaming",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends"],
    vibes: ["fun","adventure"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "VR gaming center",
  },
  {
    id: 24,
    name: "Trampoline Park",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["friends","family"],
    vibes: ["fun","adventure"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "trampoline park",
  },
  {
    id: 25,
    name: "Escape Room",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends"],
    vibes: ["fun","adventure"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "escape room",
  },
  {
    id: 26,
    name: "Laser Tag",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "laser tag arena",
  },
  {
    id: 27,
    name: "Karaoke Room",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "karaoke room",
  },
  {
    id: 28,
    name: "Indoor Badminton",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun","adventure"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "badminton court",
  },
  {
    id: 29,
    name: "Indoor Cricket",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["friends","family"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "indoor cricket nets",
  },
  {
    id: 30,
    name: "Indoor Football Turf",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["friends"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "indoor football turf",
  },
  {
    id: 32,
    name: "Pool / Snooker",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["fun","relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "snooker pool hall",
  },
  {
    id: 33,
    name: "Table Tennis Arena",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "table tennis arena",
  },
  {
    id: 35,
    name: "Go-Karting",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "high",
    groupTypes: ["couple","friends"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "go karting track",
  },
  {
    id: 36,
    name: "Ice Skating",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun","adventure"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "ice skating rink",
  },
  {
    id: 37,
    name: "Air Hockey Arena",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "air hockey arcade",
  },
  {
    id: 38,
    name: "Board Game Cafe",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun","relax"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "board game cafe",
  },
  {
    id: 103,
    name: "Mall Exploration",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","fun","food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "shopping mall",
  },

  // ─── CATEGORY 4: FAMILY + KIDS ───────────────────────────────────

  {
    id: 41,
    name: "Science Museum",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["family"],
    vibes: ["fun","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","night"],
    actionType: "maps",
    mapQuery: "science museum",
  },
  {
    id: 42,
    name: "Aquarium Visit",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family","couple"],
    vibes: ["relax","fun","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","night"],
    actionType: "maps",
    mapQuery: "aquarium",
  },
  {
    id: 43,
    name: "Zoo Visit",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["family"],
    vibes: ["fun","kids-first"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","night"],
    actionType: "maps",
    mapQuery: "zoo",
  },
  {
    id: 44,
    name: "Kids Play Zone",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["family"],
    vibes: ["fun","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "kids play zone",
  },
  {
    id: 45,
    name: "Toy Train Ride",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family"],
    vibes: ["fun","relax","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "toy train ride",
  },
  {
    id: 46,
    name: "Water Park",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "full-day",
    energyLevel: "high",
    groupTypes: ["family","friends"],
    vibes: ["fun","adventure","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 3,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "water park",
  },
  {
    id: 47,
    name: "Amusement Park",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "full-day",
    energyLevel: "high",
    groupTypes: ["family","friends"],
    vibes: ["fun","adventure","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 3,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "amusement park",
  },
  {
    id: 48,
    name: "Snow Park",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["family","couple"],
    vibes: ["fun","adventure","kids-first"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "snow park",
  },
  {
    id: 49,
    name: "Kids Craft Workshop",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family"],
    vibes: ["relax","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "kids craft workshop",
  },
  {
    id: 50,
    name: "Pottery Workshop",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "pottery workshop",
  },
  {
    id: 51,
    name: "Painting Workshop",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "painting workshop",
  },
  {
    id: 52,
    name: "DIY Art Studio",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","fun"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "art studio",
  },
  {
    id: 53,
    name: "Lego Play Zone",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family"],
    vibes: ["fun","kids-first"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 1,
    popularityScore: 1,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "lego play zone",
  },
  {
    id: 54,
    name: "Family Picnic",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["family"],
    vibes: ["relax","fun","kids-first"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "picnic spot park",
  },
  {
    id: 55,
    name: "Storytelling Session",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family"],
    vibes: ["relax","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "storytelling session kids",
  },
  {
    id: 57,
    name: "Indoor Camping Experience",
    category: "family-kids",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["family"],
    vibes: ["fun","relax","kids-first"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["evening","night"],
    actionType: null,
    mapQuery: null,
  },
  {
    id: 58,
    name: "Family Board Games Night",
    category: "family-kids",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family"],
    vibes: ["fun","relax","kids-first"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["evening","night"],
    actionType: "rules",
    mapQuery: null,
  },
  {
    id: 59,
    name: "DIY Pizza Night",
    category: "family-kids",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["family","couple","friends"],
    vibes: ["fun","food-chill","kids-first"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["afternoon","evening","night"],
    actionType: null,
    mapQuery: null,
  },
  {
    id: 60,
    name: "Cooking Together Session",
    category: "family-kids",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["family","couple","friends"],
    vibes: ["fun","food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: null,
    mapQuery: null,
  },
  {
    id: 104,
    name: "Indoor Kids Soft Play Area",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["family"],
    vibes: ["fun","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "kids soft play area",
  },
  {
    id: 115,
    name: "Heritage Monument Walk",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["family","couple","friends"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "heritage monument walk",
  },
  {
    id: 116,
    name: "Nature Park + Paddle Boating",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["family","couple","friends"],
    vibes: ["relax","fun","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "nature park boating",
  },
  {
    id: 117,
    name: "Outdoor Adventure Kids Zone",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "half-day",
    energyLevel: "high",
    groupTypes: ["family"],
    vibes: ["fun","adventure","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "adventure park kids",
  },
  {
    id: 118,
    name: "Botanical Garden Walk + Lunch",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["family","couple"],
    vibes: ["relax","food-chill","kids-first"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "botanical garden",
  },
  {
    id: 151,
    name: "Petting Farm / Animal Farm",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family","couple"],
    vibes: ["relax","fun","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "petting farm animal farm",
  },
  {
    id: 152,
    name: "Family Cycling Rental",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["family","couple","friends"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "cycling rental park",
  },
  {
    id: 153,
    name: "Outdoor Mini Golf",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family","couple","friends"],
    vibes: ["fun"],
    cityType: "metro-only",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "outdoor mini golf",
  },
  {
    id: 154,
    name: "Children Park + Ice Cream",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["family"],
    vibes: ["fun","relax","kids-first"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "children park",
  },
  {
    id: 156,
    name: "Kite Flying in Open Ground",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["family","couple","friends"],
    vibes: ["fun","adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "open ground park",
  },
  {
    id: 159,
    name: "Children's Amusement Park",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "high",
    groupTypes: ["family"],
    vibes: ["fun","adventure","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "amusement park kids",
  },
  {
    id: 161,
    name: "Outdoor Treasure Hunt (DIY)",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["family"],
    vibes: ["fun","adventure","kids-first"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["morning","afternoon"],
    actionType: null,
    mapQuery: null,
  },

  // ─── CATEGORY 5: COUPLE EXPERIENCES ──────────────────────────────

  {
    id: 61,
    name: "Sunset Drive",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax","adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["evening"],
    actionType: "maps",
    mapQuery: "scenic viewpoint sunset",
  },
  {
    id: 62,
    name: "Rooftop Cafe Date",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax","food-chill"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon","evening"],
    actionType: "maps",
    mapQuery: "rooftop cafe",
  },
  {
    id: 63,
    name: "Dessert Date",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax","food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "dessert cafe",
  },
  {
    id: 64,
    name: "Walk + Coffee",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax","food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "park walk coffee",
  },
  {
    id: 65,
    name: "Long Drive + Chai",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["relax","food-chill","adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "tea stall highway",
  },
  {
    id: 66,
    name: "Couple Pottery Workshop",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax","fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "pottery workshop",
  },
  {
    id: 67,
    name: "Couple Spa Day",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "high",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "couple spa",
  },
  {
    id: 68,
    name: "Couple Painting Session",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax","fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "painting workshop",
  },
  {
    id: 69,
    name: "Lakeside Evening",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax"],
    cityType: "metro-only",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["evening"],
    actionType: "maps",
    mapQuery: "lake park evening",
  },
  {
    id: 70,
    name: "Bookstore + Coffee Date",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "bookstore cafe",
  },
  {
    id: 71,
    name: "Candlelight Dinner",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "high",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax","food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["evening","night"],
    actionType: "maps",
    mapQuery: "candlelight dinner restaurant",
  },
  {
    id: 72,
    name: "Couple Karaoke",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "karaoke room",
  },
  {
    id: 73,
    name: "Stargazing Spot",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax","adventure"],
    cityType: "metro-only",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["night"],
    actionType: "maps",
    mapQuery: "stargazing viewpoint",
  },
  {
    id: 74,
    name: "Couple Cycling",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["couple"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "cycling track rental",
  },
  {
    id: 75,
    name: "Live Standup Comedy Show",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["evening","night"],
    actionType: "maps",
    mapQuery: "standup comedy show",
  },
  {
    id: 148,
    name: "Rooftop Bar Evening",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["relax","fun","food-chill"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["evening","night"],
    actionType: "maps",
    mapQuery: "rooftop bar restaurant",
  },
  {
    id: 150,
    name: "Laughter Show + Dinner",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["fun","food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["evening","night"],
    actionType: "maps",
    mapQuery: "standup comedy show",
  },

  // ─── CATEGORY 6: FRIENDS / GROUP OUTINGS ─────────────────────────

  {
    id: 76,
    name: "Sports Turf Match",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["friends"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "sports turf ground",
  },
  {
    id: 77,
    name: "Paintball",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "high",
    groupTypes: ["friends"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "paintball arena",
  },
  {
    id: 78,
    name: "Adventure Park",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "half-day",
    energyLevel: "high",
    groupTypes: ["friends"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "adventure park",
  },
  {
    id: 79,
    name: "Trek / Hiking Trail",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "high",
    groupTypes: ["friends"],
    vibes: ["adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "trekking hiking trail",
  },
  {
    id: 80,
    name: "Cycling Group Ride",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "high",
    groupTypes: ["friends"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "cycling track",
  },
  {
    id: 81,
    name: "Open Mic Night",
    category: "friends-group",
    location: "indoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["fun","relax"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["evening","night"],
    actionType: "maps",
    mapQuery: "open mic night",
  },
  {
    id: 82,
    name: "Standup Comedy Show",
    category: "friends-group",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["evening","night"],
    actionType: "maps",
    mapQuery: "standup comedy show",
  },
  {
    id: 83,
    name: "Music Concert",
    category: "friends-group",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["evening","night"],
    actionType: "maps",
    mapQuery: "music concert venue",
  },
  {
    id: 84,
    name: "Flea Market Visit",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun","food-chill"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "flea market",
  },
  {
    id: 85,
    name: "Pub Trivia Night",
    category: "friends-group",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["evening","night"],
    actionType: "maps",
    mapQuery: "pub trivia night",
  },
  {
    id: 86,
    name: "Live Screening Match Night",
    category: "friends-group",
    location: "indoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "sports bar live screening",
  },
  {
    id: 87,
    name: "Cafe Hopping",
    category: "friends-group",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["relax","fun","food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "cafe hopping",
  },
  {
    id: 88,
    name: "Night Drive",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["relax","adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["night"],
    actionType: "maps",
    mapQuery: "scenic night drive viewpoint",
  },
  {
    id: 89,
    name: "Photography Walk",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["couple","friends"],
    vibes: ["relax","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 1,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "photography walk heritage",
  },
  {
    id: 90,
    name: "Street Shopping Evening",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun","food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon","evening"],
    actionType: "maps",
    mapQuery: "street market shopping",
  },
  {
    id: 105,
    name: "Local Fair / Mela",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["fun","food-chill","adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "local fair mela",
  },
  {
    id: 106,
    name: "Book Fair",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","fun"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "book fair",
  },
  {
    id: 107,
    name: "Exhibition / Expo Visit",
    category: "friends-group",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "exhibition expo",
  },
  {
    id: 157,
    name: "Family Sports in the Park",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "high",
    groupTypes: ["family","couple","friends"],
    vibes: ["fun","adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "sports ground park",
  },

  // ─── CATEGORY 7: RELAX / LOW-EFFORT ──────────────────────────────

  {
    id: 91,
    name: "Park Walk",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "park walk",
  },
  {
    id: 92,
    name: "Garden Picnic",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "garden park picnic",
  },
  {
    id: 93,
    name: "Library + Coffee",
    category: "relax",
    location: "indoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 1,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "library cafe",
  },
  {
    id: 94,
    name: "Slow Cafe Evening",
    category: "relax",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["relax","food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon","evening"],
    actionType: "maps",
    mapQuery: "quiet cafe",
  },
  {
    id: 95,
    name: "Scenic Drive",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "scenic viewpoint drive",
  },
  {
    id: 96,
    name: "Temple / Spiritual Visit",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","evening","night"],
    actionType: "maps",
    mapQuery: "temple",
  },
  {
    id: 98,
    name: "Riverfront Walk",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "riverfront promenade",
  },
  {
    id: 99,
    name: "Music Listening Night",
    category: "relax",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends"],
    vibes: ["relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 1,
    timeOfDay: ["evening","night"],
    actionType: null,
    mapQuery: null,
  },
  {
    id: 100,
    name: "Balcony BBQ / Terrace Chill",
    category: "relax",
    location: "home",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["afternoon","evening","night"],
    actionType: null,
    mapQuery: null,
  },
  {
    id: 108,
    name: "Hill Viewpoint Ride",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "hill viewpoint",
  },
  {
    id: 109,
    name: "Lake Boating",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","fun","adventure"],
    cityType: "metro-only",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "lake boating",
  },
  {
    id: 110,
    name: "Night Cycling Event",
    category: "relax",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["friends"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["night"],
    actionType: "maps",
    mapQuery: "night cycling event",
  },
  {
    id: 111,
    name: "Monsoon Drive",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "scenic drive viewpoint",
  },
  {
    id: 149,
    name: "Long Drive + Dhaba Stop",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","food-chill","adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "dhaba highway restaurant",
  },
  {
    id: 155,
    name: "Nature Trail / Biodiversity Walk",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family","couple","friends"],
    vibes: ["relax","adventure","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "biodiversity park nature trail",
  },
  {
    id: 158,
    name: "Musical Fountain Show + Walk",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["family","couple","friends"],
    vibes: ["relax","fun","kids-first"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["evening","night"],
    actionType: "maps",
    mapQuery: "musical fountain show",
  },
  {
    id: 160,
    name: "Bird Watching",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["family","couple"],
    vibes: ["relax","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["morning"],
    actionType: "maps",
    mapQuery: "bird sanctuary",
  },

  // ─── CATEGORY 8: PREMIUM / SPECIAL ───────────────────────────────

  {
    id: 112,
    name: "Farmhouse Day",
    category: "premium",
    location: "outdoor",
    kidsFriendly: true,
    budget: "high",
    timeNeeded: "full-day",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "farmhouse day outing",
  },
  {
    id: 113,
    name: "Resort Day Pass",
    category: "premium",
    location: "outdoor",
    kidsFriendly: true,
    budget: "high",
    timeNeeded: "full-day",
    energyLevel: "medium",
    groupTypes: ["couple","friends","family"],
    vibes: ["relax","fun"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 3,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "resort day pass",
  },
  {
    id: 114,
    name: "Weekend Staycation",
    category: "premium",
    location: "indoor",
    kidsFriendly: true,
    budget: "high",
    timeNeeded: "full-day",
    energyLevel: "low",
    groupTypes: ["couple","family"],
    vibes: ["relax"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "hotel staycation",
  },

  // ─── CATEGORY 9: INDOOR GAMES + HOME ACTIVITIES ──────────────────

  {
    id: 119,
    name: "Pictionary",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["friends","family"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "rules",
    mapQuery: null,
  },
  {
    id: 120,
    name: "Antakshari",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends","family"],
    vibes: ["fun","relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "rules",
    mapQuery: null,
  },
  {
    id: 121,
    name: "Truth or Dare",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "rules",
    mapQuery: null,
  },
  {
    id: 122,
    name: "Dumb Charades",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["friends","family"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "rules",
    mapQuery: null,
  },
  {
    id: 123,
    name: "Tambola / Housie Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends","family"],
    vibes: ["fun","relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "rules",
    mapQuery: null,
  },
  {
    id: 124,
    name: "Carrom Tournament",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["friends","family"],
    vibes: ["fun","relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "rules",
    mapQuery: null,
  },
  {
    id: 125,
    name: "Chess / Ludo Marathon",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends","family"],
    vibes: ["fun","relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "rules",
    mapQuery: null,
  },
  {
    id: 126,
    name: "UNO / Card Games Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends","family"],
    vibes: ["fun","relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "rules",
    mapQuery: null,
  },
  {
    id: 127,
    name: "Binge Watch Party",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["friends","family"],
    vibes: ["relax","fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "watch",
    mapQuery: null,
  },
  {
    id: 128,
    name: "Kaun Banega Crorepati Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends","family"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["evening","night"],
    actionType: "rules",
    mapQuery: null,
  },
  {
    id: 129,
    name: "Rapid Fire Quiz Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["friends","family"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "rules",
    mapQuery: null,
  },
  {
    id: 130,
    name: "Murder Mystery Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun","adventure"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "rules",
    mapQuery: null,
  },
  {
    id: 131,
    name: "Houseparty Games Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon","evening","night"],
    actionType: null,
    mapQuery: null,
  },
  {
    id: 132,
    name: "Multiplayer Gaming Cafe",
    category: "indoor-games",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun","adventure"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "gaming cafe",
  },
  {
    id: 133,
    name: "PS5 / Console Gaming Lounge",
    category: "indoor-games",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening","night"],
    actionType: "maps",
    mapQuery: "console gaming lounge",
  },
  {
    id: 134,
    name: "Darts Bar",
    category: "indoor-games",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["evening","night"],
    actionType: "maps",
    mapQuery: "darts bar",
  },
  {
    id: 135,
    name: "Indoor Mini Golf",
    category: "indoor-games",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["friends","family"],
    vibes: ["fun"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "indoor mini golf",
  },
  {
    id: 136,
    name: "Cooking Class Together",
    category: "indoor-games",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends","family"],
    vibes: ["fun","food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning","afternoon"],
    actionType: "maps",
    mapQuery: "cooking class",
  },
  {
    id: 137,
    name: "Stand-up Comedy Workshop",
    category: "indoor-games",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["morning","afternoon","evening"],
    actionType: "maps",
    mapQuery: "standup comedy workshop",
  },
  {
    id: 138,
    name: "Potluck Dinner Party",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends","family"],
    vibes: ["fun","food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["afternoon","evening","night"],
    actionType: null,
    mapQuery: null,
  },
  {
    id: 139,
    name: "Chai + Gossip Evening",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends"],
    vibes: ["relax","food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon","evening","night"],
    actionType: null,
    mapQuery: null,
  },
  {
    id: 140,
    name: "DIY Cocktail / Mocktail Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends"],
    vibes: ["fun","food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["evening","night"],
    actionType: null,
    mapQuery: null,
  },
  {
    id: 141,
    name: "Bonfire + Snacks Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["friends","family"],
    vibes: ["relax","food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["evening","night"],
    actionType: null,
    mapQuery: null,
  },
  {
    id: 142,
    name: "Jam Session",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun","relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["afternoon","evening","night"],
    actionType: null,
    mapQuery: null,
  },
  {
    id: 143,
    name: "Karaoke at Home",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["friends","family"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon","evening","night"],
    actionType: null,
    mapQuery: null,
  },
  {
    id: 144,
    name: "Trivia + Snacks Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "rules",
    mapQuery: null,
  },
  {
    id: 145,
    name: "Scary Movie Marathon",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["friends"],
    vibes: ["fun","adventure"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon","evening","night"],
    actionType: "watch",
    mapQuery: null,
  },
  {
    id: 146,
    name: "Nostalgia Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["friends"],
    vibes: ["relax","fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["evening","night"],
    actionType: null,
    mapQuery: null,
  },

];