// ─── Plans Domain: Activity Catalog V3 ───────────────────────────────────────
// 145 activities fully tagged for the Plans decision engine.
// India-focused — Tier 1 + Tier 2 cities.
// Schema: id, name, category, location, kidsFriendly, budget, timeNeeded,
//         energyLevel, groupTypes, vibes, cityType, weatherSafe,
//         noveltyScore, effortScore, popularityScore, timeOfDay
//
// timeNeeded values: "1-2hr" | "2-4hr" | "half-day" | "full-day"
// timeOfDay values:  "morning" | "afternoon" | "evening" | "night"

export const ACTIVITY_CATALOG = [

  // ─── CATEGORY 1: MOVIES / ENTERTAINMENT ───────────────────────────────────

  {
    id: 1,
    name: "Movie Outing",
    category: "movies",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 2,
    name: "Drive-in Movie",
    category: "movies",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "fun"],
    cityType: "metro-only",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 3,
    name: "IMAX Experience",
    category: "movies",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 4,
    name: "Regional Cinema Night",
    category: "movies",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 5,
    name: "Open-Air Movie Screening",
    category: "movies",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "fun"],
    cityType: "metro-only",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["evening", "night"],
  },

  // ─── CATEGORY 2: FOOD + CHILL ──────────────────────────────────────────────

  {
    id: 6,
    name: "Cafe + Dessert",
    category: "food-chill",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 7,
    name: "Rooftop Dinner",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: false,
    budget: "high",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends"],
    vibes: ["relax", "food-chill"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 8,
    name: "Street Food Walk",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun", "food-chill", "adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 9,
    name: "Breakfast Ride",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple", "friends"],
    vibes: ["fun", "food-chill", "adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning"],
  },
  {
    id: 10,
    name: "Buffet Lunch",
    category: "food-chill",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon"],
  },
  {
    id: 11,
    name: "Tea + Snacks Adda",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 12,
    name: "Midnight Food Drive",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends"],
    vibes: ["fun", "food-chill", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["night"],
  },
  {
    id: 13,
    name: "Dessert Hopping",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun", "food-chill"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 14,
    name: "Food Truck Evening",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun", "food-chill"],
    cityType: "metro-only",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 15,
    name: "Fine Dining Night",
    category: "food-chill",
    location: "indoor",
    kidsFriendly: false,
    budget: "high",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends"],
    vibes: ["relax", "food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 16,
    name: "Family Restaurant Dinner",
    category: "food-chill",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family", "friends"],
    vibes: ["relax", "food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon", "evening"],
  },
  {
    id: 17,
    name: "Live Music Cafe",
    category: "food-chill",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends"],
    vibes: ["relax", "fun", "food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 18,
    name: "Chai Tapri Hangout",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends"],
    vibes: ["relax", "food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 19,
    name: "Themed Cafe Visit",
    category: "food-chill",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun", "food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon", "evening"],
  },
  {
    id: 20,
    name: "Pet Cafe Visit",
    category: "food-chill",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "fun", "food-chill"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 101,
    name: "Temple + Breakfast",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "evening", "night"],
  },
  {
    id: 102,
    name: "Flea + Food Market",
    category: "food-chill",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun", "food-chill", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },

  // ─── CATEGORY 3: FUN INDOOR ACTIVITIES ────────────────────────────────────

  {
    id: 21,
    name: "Bowling",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 22,
    name: "Arcade / Gaming Zone",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 23,
    name: "VR Gaming",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple", "friends"],
    vibes: ["fun", "adventure"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 24,
    name: "Trampoline Park",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["friends", "family"],
    vibes: ["fun", "adventure"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 25,
    name: "Escape Room",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["couple", "friends"],
    vibes: ["fun", "adventure"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 26,
    name: "Laser Tag",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["friends", "family"],
    vibes: ["fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 27,
    name: "Karaoke Room",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple", "friends"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 28,
    name: "Indoor Badminton",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun", "adventure"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 29,
    name: "Indoor Cricket",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["friends", "family"],
    vibes: ["fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 30,
    name: "Indoor Football Turf",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["friends"],
    vibes: ["fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 32,
    name: "Pool / Snooker",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends"],
    vibes: ["fun", "relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 33,
    name: "Table Tennis Arena",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 35,
    name: "Go-Karting",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "high",
    groupTypes: ["couple", "friends"],
    vibes: ["fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 36,
    name: "Ice Skating",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun", "adventure"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 37,
    name: "Air Hockey Arena",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 38,
    name: "Board Game Cafe",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun", "relax"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 103,
    name: "Mall Exploration",
    category: "indoor-fun",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "fun", "food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },

  // ─── CATEGORY 4: FAMILY + KIDS ────────────────────────────────────────────

  {
    id: 41,
    name: "Science Museum",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["family"],
    vibes: ["fun", "kids-first"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "night"],
  },
  {
    id: 42,
    name: "Aquarium Visit",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family", "couple"],
    vibes: ["relax", "fun", "kids-first"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "night"],
  },
  {
    id: 43,
    name: "Zoo Visit",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["family"],
    vibes: ["fun", "kids-first"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "night"],
  },
  {
    id: 44,
    name: "Kids Play Zone",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["family"],
    vibes: ["fun", "kids-first"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 45,
    name: "Toy Train Ride",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family"],
    vibes: ["fun", "relax", "kids-first"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 46,
    name: "Water Park",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "full-day",
    energyLevel: "high",
    groupTypes: ["family", "friends"],
    vibes: ["fun", "adventure", "kids-first"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 3,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 47,
    name: "Amusement Park",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "full-day",
    energyLevel: "high",
    groupTypes: ["family", "friends"],
    vibes: ["fun", "adventure", "kids-first"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 3,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 48,
    name: "Snow Park",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["family", "couple"],
    vibes: ["fun", "adventure", "kids-first"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 49,
    name: "Kids Craft Workshop",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family"],
    vibes: ["relax", "kids-first"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 50,
    name: "Pottery Workshop",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 51,
    name: "Painting Workshop",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 52,
    name: "DIY Art Studio",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "fun"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 53,
    name: "Lego Play Zone",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family"],
    vibes: ["fun", "kids-first"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 1,
    popularityScore: 1,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 54,
    name: "Family Picnic",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["family"],
    vibes: ["relax", "fun", "kids-first"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 55,
    name: "Storytelling Session",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family"],
    vibes: ["relax", "kids-first"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 57,
    name: "Indoor Camping Experience",
    category: "family-kids",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["family"],
    vibes: ["fun", "relax", "kids-first"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 58,
    name: "Family Board Games Night",
    category: "family-kids",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["family"],
    vibes: ["fun", "relax", "kids-first"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 59,
    name: "DIY Pizza Night",
    category: "family-kids",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["family", "couple", "friends"],
    vibes: ["fun", "food-chill", "kids-first"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 60,
    name: "Cooking Together Session",
    category: "family-kids",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["family", "couple", "friends"],
    vibes: ["fun", "food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 104,
    name: "Indoor Kids Soft Play Area",
    category: "family-kids",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["family"],
    vibes: ["fun", "kids-first"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },

  // ─── CATEGORY 5: COUPLE EXPERIENCES ──────────────────────────────────────

  {
    id: 61,
    name: "Sunset Drive",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax", "adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["evening"],
  },
  {
    id: 62,
    name: "Rooftop Cafe Date",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax", "food-chill"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon", "evening"],
  },
  {
    id: 63,
    name: "Dessert Date",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax", "food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 64,
    name: "Walk + Coffee",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax", "food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 65,
    name: "Long Drive + Chai",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends"],
    vibes: ["relax", "food-chill", "adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 66,
    name: "Couple Pottery Workshop",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax", "fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 67,
    name: "Couple Spa Day",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "high",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 68,
    name: "Couple Painting Session",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax", "fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 69,
    name: "Lakeside Evening",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax"],
    cityType: "metro-only",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["evening"],
  },
  {
    id: 70,
    name: "Bookstore + Coffee Date",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 71,
    name: "Candlelight Dinner",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "high",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax", "food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 72,
    name: "Couple Karaoke",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 73,
    name: "Stargazing Spot",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax", "adventure"],
    cityType: "metro-only",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["night"],
  },
  {
    id: 74,
    name: "Couple Cycling",
    category: "couple",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["couple"],
    vibes: ["fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 75,
    name: "Live Standup Comedy Show",
    category: "couple",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["evening", "night"],
  },

  // ─── CATEGORY 6: FRIENDS / GROUP OUTINGS ──────────────────────────────────

  {
    id: 76,
    name: "Sports Turf Match",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["friends"],
    vibes: ["fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 77,
    name: "Paintball",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "high",
    groupTypes: ["friends"],
    vibes: ["fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 78,
    name: "Adventure Park",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "half-day",
    energyLevel: "high",
    groupTypes: ["friends"],
    vibes: ["fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 79,
    name: "Trek / Hiking Trail",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "high",
    groupTypes: ["friends"],
    vibes: ["adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 80,
    name: "Cycling Group Ride",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "high",
    groupTypes: ["friends"],
    vibes: ["fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 81,
    name: "Open Mic Night",
    category: "friends-group",
    location: "indoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends"],
    vibes: ["fun", "relax"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 82,
    name: "Standup Comedy Show",
    category: "friends-group",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 83,
    name: "Music Concert",
    category: "friends-group",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple", "friends"],
    vibes: ["fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 84,
    name: "Flea Market Visit",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun", "food-chill"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 85,
    name: "Pub Trivia Night",
    category: "friends-group",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 86,
    name: "Live Screening Match Night",
    category: "friends-group",
    location: "indoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 87,
    name: "Cafe Hopping",
    category: "friends-group",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends"],
    vibes: ["relax", "fun", "food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 88,
    name: "Night Drive",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends"],
    vibes: ["relax", "adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["night"],
  },
  {
    id: 89,
    name: "Photography Walk",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["couple", "friends"],
    vibes: ["relax", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 1,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 90,
    name: "Street Shopping Evening",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun", "food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon", "evening"],
  },
  {
    id: 105,
    name: "Local Fair / Mela",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["fun", "food-chill", "adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 106,
    name: "Book Fair",
    category: "friends-group",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "fun"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 107,
    name: "Exhibition / Expo Visit",
    category: "friends-group",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "fun"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },

  // ─── CATEGORY 7: RELAX / LOW-EFFORT ──────────────────────────────────────

  {
    id: 91,
    name: "Park Walk",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 92,
    name: "Garden Picnic",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 93,
    name: "Library + Coffee",
    category: "relax",
    location: "indoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple"],
    vibes: ["relax"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 1,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 94,
    name: "Slow Cafe Evening",
    category: "relax",
    location: "indoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends"],
    vibes: ["relax", "food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon", "evening"],
  },
  {
    id: 95,
    name: "Scenic Drive",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 96,
    name: "Temple / Spiritual Visit",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "evening", "night"],
  },
  {
    id: 98,
    name: "Riverfront Walk",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 99,
    name: "Music Listening Night",
    category: "relax",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends"],
    vibes: ["relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 1,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 100,
    name: "Balcony BBQ / Terrace Chill",
    category: "relax",
    location: "home",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 108,
    name: "Hill Viewpoint Ride",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 109,
    name: "Lake Boating",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "fun", "adventure"],
    cityType: "metro-only",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 110,
    name: "Night Cycling Event",
    category: "relax",
    location: "outdoor",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "high",
    groupTypes: ["friends"],
    vibes: ["fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["night"],
  },
  {
    id: 111,
    name: "Monsoon Drive",
    category: "relax",
    location: "outdoor",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "adventure"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },

  // ─── CATEGORY 8: PREMIUM / SPECIAL ───────────────────────────────────────

  {
    id: 112,
    name: "Farmhouse Day",
    category: "premium",
    location: "outdoor",
    kidsFriendly: true,
    budget: "high",
    timeNeeded: "full-day",
    energyLevel: "medium",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 113,
    name: "Resort Day Pass",
    category: "premium",
    location: "outdoor",
    kidsFriendly: true,
    budget: "high",
    timeNeeded: "full-day",
    energyLevel: "medium",
    groupTypes: ["couple", "friends", "family"],
    vibes: ["relax", "fun"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 3,
    effortScore: 3,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 114,
    name: "Weekend Staycation",
    category: "premium",
    location: "indoor",
    kidsFriendly: true,
    budget: "high",
    timeNeeded: "full-day",
    energyLevel: "low",
    groupTypes: ["couple", "family"],
    vibes: ["relax"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 3,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 115,
    name: "Heritage Monument Walk",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["family", "couple", "friends"],
    vibes: ["fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 116,
    name: "Nature Park + Paddle Boating",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "half-day",
    energyLevel: "medium",
    groupTypes: ["family", "couple", "friends"],
    vibes: ["relax", "fun", "kids-first"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 117,
    name: "Outdoor Adventure Kids Zone",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "half-day",
    energyLevel: "high",
    groupTypes: ["family"],
    vibes: ["fun", "adventure", "kids-first"],
    cityType: "metro-tier2",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 118,
    name: "Botanical Garden Walk + Lunch",
    category: "family-kids",
    location: "outdoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["family", "couple"],
    vibes: ["relax", "food-chill", "kids-first"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },

  // ─── CATEGORY 9: INDOOR GAMES + HOME ACTIVITIES ───────────────────────────

  {
    id: 119,
    name: "Pictionary",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["friends", "family"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 120,
    name: "Antakshari",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends", "family"],
    vibes: ["fun", "relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 121,
    name: "Truth or Dare",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 122,
    name: "Dumb Charades",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["friends", "family"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 123,
    name: "Tambola / Housie Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends", "family"],
    vibes: ["fun", "relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 124,
    name: "Carrom Tournament",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["friends", "family"],
    vibes: ["fun", "relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 125,
    name: "Chess / Ludo Marathon",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends", "family"],
    vibes: ["fun", "relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 126,
    name: "UNO / Card Games Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends", "family"],
    vibes: ["fun", "relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 127,
    name: "Binge Watch Party",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["friends", "family"],
    vibes: ["relax", "fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 128,
    name: "Kaun Banega Crorepati Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends", "family"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 129,
    name: "Rapid Fire Quiz Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["friends", "family"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 130,
    name: "Murder Mystery Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun", "adventure"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 131,
    name: "Houseparty Games Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 132,
    name: "Multiplayer Gaming Cafe",
    category: "indoor-games",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun", "adventure"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 133,
    name: "PS5 / Console Gaming Lounge",
    category: "indoor-games",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening", "night"],
  },
  {
    id: 134,
    name: "Darts Bar",
    category: "indoor-games",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 135,
    name: "Indoor Mini Golf",
    category: "indoor-games",
    location: "indoor",
    kidsFriendly: true,
    budget: "medium",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["friends", "family"],
    vibes: ["fun"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 136,
    name: "Cooking Class Together",
    category: "indoor-games",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends", "family"],
    vibes: ["fun", "food-chill"],
    cityType: "metro-tier2",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["morning", "afternoon"],
  },
  {
    id: 137,
    name: "Stand-up Comedy Workshop",
    category: "indoor-games",
    location: "indoor",
    kidsFriendly: false,
    budget: "medium",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "metro-only",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["morning", "afternoon", "evening"],
  },
  {
    id: 138,
    name: "Potluck Dinner Party",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends", "family"],
    vibes: ["fun", "food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 3,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 139,
    name: "Chai + Gossip Evening",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends"],
    vibes: ["relax", "food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 1,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 140,
    name: "DIY Cocktail / Mocktail Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends"],
    vibes: ["fun", "food-chill"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 141,
    name: "Bonfire + Snacks Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["friends", "family"],
    vibes: ["relax", "food-chill"],
    cityType: "all",
    weatherSafe: false,
    noveltyScore: 2,
    effortScore: 2,
    popularityScore: 2,
    timeOfDay: ["evening", "night"],
  },
  {
    id: 142,
    name: "Jam Session",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "medium",
    groupTypes: ["friends"],
    vibes: ["fun", "relax"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 3,
    effortScore: 2,
    popularityScore: 1,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 143,
    name: "Karaoke at Home",
    category: "indoor-games",
    location: "home",
    kidsFriendly: true,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "medium",
    groupTypes: ["friends", "family"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 3,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 144,
    name: "Trivia + Snacks Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "1-2hr",
    energyLevel: "low",
    groupTypes: ["friends"],
    vibes: ["fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 145,
    name: "Scary Movie Marathon",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "half-day",
    energyLevel: "low",
    groupTypes: ["friends"],
    vibes: ["fun", "adventure"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["afternoon", "evening", "night"],
  },
  {
    id: 146,
    name: "Nostalgia Night",
    category: "indoor-games",
    location: "home",
    kidsFriendly: false,
    budget: "low",
    timeNeeded: "2-4hr",
    energyLevel: "low",
    groupTypes: ["friends"],
    vibes: ["relax", "fun"],
    cityType: "all",
    weatherSafe: true,
    noveltyScore: 2,
    effortScore: 1,
    popularityScore: 2,
    timeOfDay: ["evening", "night"],
  },
];